dist: trusty
sudo: required
language: cpp
install:
    - sudo apt-get update -q
    - sudo apt-get install git-buildpackage devscripts equivs
before_script:
    - sudo mount -t tmpfs tmpfs /tmp
    - git checkout 5.6-uber
    - /bin/bash build-ps/jenkins-prebuild.sh
    - sudo mk-build-deps -i && git clean -f
env:
    global:
        - MYSQL_TEST_PARAM="--tmpdir=/tmp/mysql-test/tmp --vardir=/tmp/mysql-test"
script: git-buildpackage --git-builder="debuild --preserve-env -i -I" --git-submodules --git-upstream-tree=branch --git-upstream-branch=5.6-uber --git-verbose --git-ignore-branch --git-ignore-new
